version: '3.8'
services:

  blog:
    build: ..
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
    depends_on:
      - mysqldb
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/appdb
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=secret
